name: NPM Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"

      - name: Check version change
        id: check
        run: |
          PREV_VERSION=$(git show HEAD^:package.json | grep '"version":' | cut -d '"' -f4)
          CURRENT_VERSION=$(cat package.json | grep '"version":' | cut -d '"' -f4)
          if [ "$PREV_VERSION" != "$CURRENT_VERSION" ]; then
            echo "Version changed from $PREV_VERSION to $CURRENT_VERSION"
            echo "version_changed=true" >> $GITHUB_OUTPUT
          else
            echo "Version unchanged"
            echo "version_changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Install dependencies
        if: steps.check.outputs.version_changed == 'true'
        run: npm ci

      - name: Build
        if: steps.check.outputs.version_changed == 'true'
        run: npm run build

      - name: Publish to NPM
        if: steps.check.outputs.version_changed == 'true'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
